### ISSUE TITLE
Release on crates.io

### ISSUE THREAD

**Issue by fabianfreyer** [fubarnetes/webterm#31]
Currently, this can't be released on crates.io, until the patches to tokio-pty-process are upstreamed:
- [x] `tokio-pty-process` is released with the following PRs merged:
- [X] https://github.com/pkgw/stund/pull/50
- [X] https://github.com/pkgw/stund/pull/49
- [X] https://github.com/pkgw/stund/pull/48
- [X] https://github.com/pkgw/stund/pull/44
